title: Rojana Binte Azad
logo: /assets/img/propic_wifey.jpeg
#description: An individual fascinated by the potential of intelligent machines to explore and explain the complexities of the quantum universe.
email: <a href="mailto:rojanaoyshi0111@gmail.com">rojanaoyshi0111@gmail.com</a>
show_downloads: false
# google_analytics: G-ZLK2GHB055
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  - name: Academics
    link: ./academics.html
  # - name: Teaching
  #   link: ./teaching.html
  - name: Research
    link: ./research.html
  # - name: Seminars
  #   link: ./seminars.html
  # - name: Others
  #   link: ./others.html
  
  - name: Google Scholar
    icon: <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" style="vertical-align:-0.125em;" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><path d="M5.242 13.769L0 9.5L12 0l12 9.5l-5.242 4.269C17.548 11.249 14.978 9.5 12 9.5c-2.977 0-5.548 1.748-6.758 4.269zM12 10a7 7 0 1 0 0 14a7 7 0 0 0 0-14z" fill="currentColor"/></svg>
    link: https://scholar.google.com/citations?user=RsHHD8IAAAAJ&hl=en&oi=ao
  # - name: GitHub
  #   icon: <i class="fa-brands fa-github"></i>
  #   link: https://github.com/chacconed
  - name: Linkedin
    icon: <i class="fab fa-linkedin-in"></i>
    link: https://www.linkedin.com/in/rojana-azad-101239214/
    
  - name: Research Gate
    icon: <svg xmlns="http://www.w3.org/2000/svg" aria-label="Research Gate" role="img" viewBox="0 0 512 512"><rect width="512" height="512" rx="15%" fill="#00d0af"/><g fill="#feffff"><path d="m271 383c-15-4-23-10-36-26-9-12-26-39-35-53l-6-11h-24l0 34c1 43 0 42 19 45l10 1 0 4 0 4h-80l0-4c0-4 1-4 9-6 10-2 14-5 15-14 1-4 1-31 1-79-0-70-1-72-3-77-3-5-7-7-18-8-4-1-5-1-5-5v-4l43-1c55-1 65 0 81 11 15 10 22 24 20 43-1 21-17 42-37 50-4 1-7 3-7 3 0 2 17 28 28 43 15 21 27 32 36 37 4 2 9 3 10 3 3 0 3 1 3 4 0 3-1 5-2 5-5 2-19 2-26 0zm-57-109c14-7 22-18 23-35 1-13-2-22-10-30-9-10-25-14-48-12l-10 1v39c0 36 0 40 2 40 1 0 9 1 18 0 14-0 17-1 24-4z"/><path d="m321 228c-25-4-34-20-32-61 1-21 3-30 11-38 7-7 13-9 25-10 13-1 21 2 29 8 5 4 9 10 9 13 0 1-3 2-6 4l-6 3-3-3c-5-6-9-9-14-11-10-3-20 2-25 11-3 5-3 6-3 29 0 22 0 25 3 29 4 7 12 11 21 10 13-1 20-10 20-24v-7l-10-0-10-0v-13h36l-0 15c-0 12-1 16-3 22-6 15-23 24-42 22z"/></g></svg>
    link: https://www.researchgate.net/profile/Rojana-Azad
  - name: ''



  # - name: Project Repository
  #   icon: <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" style="vertical-align:-0.125em;" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 16 16"><g fill="currentColor"><path d="M12.643 15C13.979 15 15 13.845 15 12.5V5H1v7.5C1 13.845 2.021 15 3.357 15h9.286zM5.5 7h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1zM.8 1a.8.8 0 0 0-.8.8V3a.8.8 0 0 0 .8.8h14.4A.8.8 0 0 0 16 3V1.8a.8.8 0 0 0-.8-.8H.8z"/></g></svg>
  #   link: https://github.com/BDHU/minimalist

# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error â€”
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
# github: [metadata]
